apiVersion : apps/v1
kind: Deployment
metadata:
  name: maanaiomaanacurrency 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maanaiomaanacurrency
  template:
    metadata:
      labels:
        app: maanaiomaanacurrency 
    spec:
      containers:
        - name: maanaiomaanacurrency 
          image: services.azurecr.io/maanaiomaanacurrency
          ports:
          - containerPort: 8050