apiVersion : apps/v1
kind: Deployment
metadata:
  name: maanaiomaanacurrency 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maanaiomaanacurrency
  template:
    metadata:
      labels:
        app: maanaiomaanacurrency
    spec:
      containers:      
        - name: maanaiomaanacurrency
          env:
          - name: PORT
            value: "#{PORT}#"
          - name: SERVICE_ID
            value: "#{SERVICE_ID}#"
          image: services.azurecr.io/maana-currency:v2.0.1          
          ports:
          - containerPort: 8050                
          resources:
            limits:
              cpu: 400m
              memory: 500Mi
            requests:
              cpu: 400m
              memory: 500Mi
        