apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: maana-currency
    hasuraService: custom
  name: maana-currency
  namespace: default
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: maana-currency
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maana-currency
    spec:
      containers:
      - image: hasura/base-git-image:0.7
        imagePullPolicy: IfNotPresent
        name: maana-currency
        ports:
        - containerPort: 8050
          protocol: TCP
        resources: {}
        args:
          - "PORT=8050"
          - "SERVICE_ID=maana-currency"
      securityContext: {}
      terminationGracePeriodSeconds: 0
status: {}