apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: maana-currency
    hasuraService: custom
  name: maana-currency
  namespace: default
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: maana-currency
  type: LoadBalancer
status:
  loadBalancer: {}