# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: azure/aks-set-context@v1
      with:
          creds: '${{ secrets.ROIE_DEV_AZURE }}' # Azure credentials
          resource-group: '${{ secrets.AZURE_RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.AZURE_KUBERNETES_CLUSTER }}'
      id: login
    
    - uses: Azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        password: ${{ secrets.REGISTRY_PASSWORD }}
        username: ${{ secrets.REGISTRY_USERNAME }}        
    
    - run: |
        docker build . -t docker.pkg.github.com/maana-currency:${{ github.sha }}
        docker push docker.pkg.github.com/maana-currency:${{ github.sha }}
      
#     - uses: Azure/k8s-set-context@v1
#       with:
#         kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: docker.pkg.github.com
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'kompose'
        dockerComposeFile: './docker-compose-resolved.yml'
        kompose-version: 'latest' 

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          docker.pkg.github.com/maana-currency:${{ github.sha }}
        imagepullsecrets: |
          demo-k8s-secret
